services:
  php-web:
    build: ./php-web
    ports:
      - "80:80"
    volumes:
      - ./php-web/www:/var/www
      - ./php-web/php.ini:/usr/local/etc/php/php.ini
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql:db
  
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped
    
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql:db